name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore Packages
      run: nuget restore
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build application 
      run: |
        MSBuild.exe PasswordHash.sln /p:Platform="Any CPU" /p:Configuration="Release"
        echo test, and deploy your project.
    - uses: actions/upload-artifact@v1
      with:
        name: PasswordHasher_MSBuild
        path: ./
 
